# syntax=docker/dockerfile:1.20

#
# This file is automatically generated by `./update_stable.py` at 2026-01-05 20:16:51.187790
# Manual modifications will be overwritten
#

FROM --platform=linux/amd64 docker.gosh.sh/debian@sha256:ce9b5c9a49f6e6bd67a98b9bd7874969c594a0c5fd15a7bf62afe53f9f82feaa AS base-amd64
FROM --platform=linux/arm64 docker.gosh.sh/debian@sha256:062f54f80b1000294be2abc69d0c654cb88710976251c920ed398c647a5d6c75 AS base-arm64

FROM base-${TARGETARCH}
