# syntax=docker/dockerfile:1.14

#
# This file is automatically generated by `./update_stable.py` at 2025-04-03 20:01:00.437920
# Manual modifications will be overwritten
#

FROM --platform=linux/amd64 docker.gosh.sh/debian@sha256:90f22ded60f94d1236931bcc15b8d62331e1e3954a9b690868af24a81031f41c AS base-amd64
FROM --platform=linux/arm64 docker.gosh.sh/debian@sha256:f3b05534f503eead821c13f31d2673bb0ba9c3f1ce45c0902bbc6f4565b54a03 AS base-arm64

FROM base-${TARGETARCH}
