# syntax=docker/dockerfile:1.20

#
# This file is automatically generated by `./update_stable.py` at 2026-01-05 20:16:53.952250
# Manual modifications will be overwritten
#

FROM --platform=linux/amd64 docker.gosh.sh/plugin-docker-buildx-cond@sha256:50078b98c9ee659319733cd111bfe6091a6186d434deb9e172f574d721e92e31 AS base-amd64
FROM --platform=linux/arm64 docker.gosh.sh/plugin-docker-buildx-cond@sha256:2303e3d37a952e90a7a193a629949e5c106ca9cac48d0d664b7a5411126e323d AS base-arm64

FROM base-${TARGETARCH}

RUN test -e /usr/local/bin/docker-original || mv /usr/local/bin/docker /usr/local/bin/docker-original
COPY --chmod=755 docker/plugin-docker-buildx-cond/docker-wrapper.sh /usr/local/bin/docker
