# syntax=docker/dockerfile:1.20

#
# This file is automatically generated by `./update_stable.py` at 2026-01-05 18:42:34.914314
# Manual modifications will be overwritten
#

FROM --platform=linux/amd64 docker.gosh.sh/plugin-docker-buildx-cond@sha256:f64942bbb264f0268a1b1f9546fca75973afa685181354afc7cdf78ffc5d0593 AS base-amd64
FROM --platform=linux/arm64 docker.gosh.sh/plugin-docker-buildx-cond@sha256:9c88ec5e01744dca1e3f64b9167ffc97a43a2ef03496d87f962d8f3ff2d9956e AS base-arm64

FROM base-${TARGETARCH}
