# syntax=docker/dockerfile:1.14

#
# This file is automatically generated by `./update_stable.py` at 2025-03-17 11:19:08.976772
# Manual modifications will be overwritten
#

FROM --platform=linux/amd64 docker.gosh.sh/rust@sha256:968692c0c3c5876c5807792ec5019c468769164dd12ce4f82c5aa6c2bf0feb3c AS base-amd64
FROM --platform=linux/arm64 docker.gosh.sh/rust@sha256:e784facf50491b46c927e5a7c26561494428bc9c21f66591738c607bdb3c0823 AS base-arm64

FROM base-${TARGETARCH}
