# syntax=docker/dockerfile:1.14

#
# This file is automatically generated by `./update_stable.py` at 2025-06-13 10:51:24.645022
# Manual modifications will be overwritten
#

FROM --platform=linux/amd64 docker.gosh.sh/rust@sha256:303d9188d7988e359c5a06c256dd9f73655461a8b7d05abcdebddc339bbc5083 AS base-amd64
FROM --platform=linux/arm64 docker.gosh.sh/rust@sha256:3cb1b99adc5fc09202cec4a55ca7dc2e75b47181fb794a16e60dfc0624cf0db4 AS base-arm64

FROM base-${TARGETARCH}
