# syntax=docker/dockerfile:1.23

#
# This file is automatically generated by `./update_stable.py` at 2026-05-19 13:07:12.873238
# Manual modifications will be overwritten
#

FROM --platform=linux/amd64 docker.gosh.sh/rust@sha256:e333ca5b40dd78782153e777b6107898556882f9697143b29240e05a6f8c7250 AS base-amd64
FROM --platform=linux/arm64 docker.gosh.sh/rust@sha256:0d702cee17daf8fc8d01e6471a34861d70a1ee30100a98aa772a0558feea0c6a AS base-arm64

FROM base-${TARGETARCH}
