---
when:
  - event: cron
    cron: cron_build
  - event: push
    branch:
      - main

variables:
  - &build_plugin "woodpeckerci/plugin-docker-buildx:latest"
  - docker_logins: &docker_logins
      - registry: https://docker.gosh.sh
        username: woodpecker
        password:
          from_secret: DOCKER_GOSH_SH_PASSWORD

steps:
  rust:
    depends_on: []
    image: *build_plugin
    settings:
      logins: *docker_logins
      platforms: linux/amd64,linux/arm64
      repo: docker.gosh.sh/rust
      dockerfile: docker/rust.dockerfile
      cache_from:
        - docker.gosh.sh/rust

  debian:
    depends_on: []
    image: *build_plugin
    settings:
      logins: *docker_logins
      platforms: linux/amd64,linux/arm64
      repo: docker.gosh.sh/debian
      dockerfile: docker/debian.dockerfile

  dragonfly:
    depends_on: []
    image: *build_plugin
    settings:
      logins: *docker_logins
      platforms: linux/amd64,linux/arm64
      repo: docker.gosh.sh/dragonfly
      dockerfile: docker/dragonfly.dockerfile

  bun:
    depends_on: []
    image: *build_plugin
    settings:
      logins: *docker_logins
      platforms: linux/amd64,linux/arm64
      repo: docker.gosh.sh/bun
      dockerfile: docker/bun.dockerfile

  ansible:
    depends_on: []
    image: *build_plugin
    settings:
      logins: *docker_logins
      platforms: linux/amd64,linux/arm64
      repo: docker.gosh.sh/ansible
      dockerfile: docker/ansible.dockerfile
