---
when:
  - event: cron
    cron: cron_build
  - event: push
    branch:
      - main

variables:
  - &build_plugin "woodpeckerci/plugin-docker-buildx:latest"
  - docker_logins: &docker_logins
      - registry: https://docker.gosh.sh
        username: woodpecker
        password:
          from_secret: DOCKER_GOSH_SH_PASSWORD

steps:
  plugin_docker_buildx_cond:
    depends_on: []
    image: *build_plugin
    settings:
      logins: *docker_logins
      platforms: linux/amd64,linux/arm64
      repo: docker.gosh.sh/plugin-docker-buildx-cond
      context: docker/plugin-docker-buildx-cond
      dockerfile: docker/plugin-docker-buildx-cond/Dockerfile

  rust:
    depends_on: []
    image: *build_plugin
    settings:
      logins: *docker_logins
      platforms: linux/amd64,linux/arm64
      repo: docker.gosh.sh/rust
      dockerfile: docker/rust.dockerfile

  taplo:
    depends_on: []
    image: *build_plugin
    settings:
      logins: *docker_logins
      platforms: linux/amd64,linux/arm64
      repo: docker.gosh.sh/taplo
      dockerfile: docker/taplo.dockerfile

  debian-slim:
    depends_on: []
    image: *build_plugin
    settings:
      logins: *docker_logins
      platforms: linux/amd64,linux/arm64
      repo: docker.gosh.sh/debian
      tag: slim
      dockerfile: docker/debian-slim.dockerfile

  debian:
    depends_on: []
    image: *build_plugin
    settings:
      logins: *docker_logins
      platforms: linux/amd64,linux/arm64
      repo: docker.gosh.sh/debian
      dockerfile: docker/debian.dockerfile

  dragonfly:
    depends_on: []
    image: *build_plugin
    settings:
      logins: *docker_logins
      platforms: linux/amd64,linux/arm64
      repo: docker.gosh.sh/dragonfly
      dockerfile: docker/dragonfly.dockerfile

  gitleaks:
    depends_on: []
    image: *build_plugin
    settings:
      logins: *docker_logins
      platforms: linux/amd64,linux/arm64
      repo: docker.gosh.sh/gitleaks
      dockerfile: docker/gitleaks.dockerfile

  nginx:
    depends_on: []
    image: *build_plugin
    settings:
      logins: *docker_logins
      platforms: linux/amd64,linux/arm64
      repo: docker.gosh.sh/nginx
      dockerfile: docker/nginx.dockerfile

  bun:
    depends_on: []
    image: *build_plugin
    settings:
      logins: *docker_logins
      platforms: linux/amd64,linux/arm64
      repo: docker.gosh.sh/bun
      dockerfile: docker/bun.dockerfile

  ansible:
    depends_on: []
    image: *build_plugin
    settings:
      logins: *docker_logins
      platforms: linux/amd64,linux/arm64
      repo: docker.gosh.sh/ansible
      dockerfile: docker/ansible.dockerfile
